language: clojure
lein: lein2

install:
    - cd client
    - npm install -q
    - npm install -q -g grunt-cli
    - bower install
    - bundle install
    - cd ..

script:
    - cd client
    - grunt test
    - cd ..
    - cd server
    - lein2 test
