language: clojure
lein: lein2

env: >
    WORKOUT_TRACKER_DB_NAME=workout_tracker_test
    WORKOUT_TRACKER_DB_APP_USER=postgres
    WORKOUT_TRACKER_DB_MIG_USER=postgres
    WORKOUT_TRACKER_DB_HOST=localhost
    WORKOUT_TRACKER_DB_PORT=5432

before_script:
    - psql -c 'create database workout_tracker_test;' -U postgres

install:
    - cd client
    - npm install -q
    - npm install -q -g grunt-cli
    - npm install -q -g bower
    - bower install
    - bundle install
    - cd ..

script:
    - cd client
    - grunt
    - cd ..
    - cd server
    - lein2 test
