language: clojure
lein: lein2

install:
    - cd client
    - npm install
    - npm install -g grunt-cli
    - bundle install
    - cd ..

test:
    - cd client
    - grunt test
    - cd ..
    - cd server
    - lein2 test
